# Generated by Django 5.0 on 2024-01-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_user_alter_bugreport_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
    ]
