# Generated by Django 4.2.6 on 2024-01-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_user_alter_bugreport_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
    ]
