# Generated by Django 4.2.6 on 2024-01-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bugreport_account'),
        ('app', '0006_bugreport_date_created_alter_bugreport_account'),
    ]

    operations = [
    ]
