# Generated by Django 4.2.6 on 2024-01-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20240111_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports_messages', to='app.message'),
        ),
    ]
