# Generated by Django 4.2.6 on 2024-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bugreport_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
