# Generated by Django 4.2.6 on 2024-01-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bugreport_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='messages',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='bug_reports_messages', to='app.message'),
        ),
    ]
