# Generated by Django 4.2.6 on 2024-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_bugreport_most_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
