# Generated by Django 4.2.6 on 2024-01-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_bugreport_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.message'),
        ),
    ]
